---
galaxy_info:
  author: Luc Stroobant
  description: Icinga2 master server installation

  license: MIT

  min_ansible_version: 2.7

  platforms:
    - name: EL
      versions:
        - 7
    - name: Debian
      version:
        - 10
    - name: Ubuntu
      version:
        - 18

  galaxy_tags:
    - icinga
    - icinga2
    - master

dependencies: []
