---
galaxy_info:
  author: Luc Stroobant
  description: Icinga2 hostconfig

  license: MIT

  min_ansible_version: 2.8

  platforms:
    - name: EL
      versions:
        - 7
    - name: Debian
      version:
        - 9
        - 10
    - name: Ubuntu
      version:
        - 16
        - 18

  galaxy_tags:
    - icinga2
    - hostconfig

dependencies: []
