---
- name: load database schema
  mysql_db:
    state: import
    name: "{{ icingaweb_db_name }}"
    target: "{{ icinga2_icingaweb2_schema }}"

- name: restart httpd
  service:
    name: httpd
    state: restarted
    enabled: true

- name: restart apache2
  service:
    name: apache2
    state: restarted
    enabled: true
