---
galaxy_info:
  author: Luc Stroobant
  description: install monitoring plugins and eventhandlers

  license: MIT

  min_ansible_version: 2.7

  platforms:
    - name: EL
      versions:
        - 6
        - 7
    - name: Debian
      version:
        - 9
        - 10
    - name: Ubuntu
      version:
        - 14
        - 18

  galaxy_tags:
    - monitoring
    - nagios
    - plugins

dependencies: []
