---
__monitoring_plugins_path: /usr/lib/nagios/plugins
__monitoring_plugins_user: nagios

__monitoring_plugins_Debian_all:
  pkgs:
    - monitoring-plugins

__monitoring_plugins_Debian_10:
  pkgs: []

__monitoring_plugins_custom_Debian_10: []

__monitoring_plugins_Debian_9:
  pkgs: []

__monitoring_plugins_custom_Debian_9: []
